In [2]:
import numpy as np

In [3]:
arr = np.random.randn(3,5)
arr

array([[ 0.75663337, -0.68619708, -1.59977064, -0.09050398, -0.72455802],
       [ 0.47806253, -1.51399443,  0.17391022,  1.14385979,  0.26754446],
       [-0.29059446, -0.14803879, -0.83096088, -0.3464901 ,  0.0956119 ]])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.dtype

dtype('float64')

In [6]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [10]:
print(np.eye(5,8,2))

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In [13]:
print(np.diag(np.eye(5,8)))

[1. 1. 1. 1. 1.]


In [15]:
print(np.arange(6,23,2.5))

[ 6.   8.5 11.  13.5 16.  18.5 21. ]


In [16]:
fun=lambda x,y : x+y
print(np.fromfunction(fun,(4,4)))

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


In [18]:
fun=lambda x,y : x+y
print(np.sum(np.fromfunction(fun,(4,4))))

48.0


In [19]:
fun=lambda x,y : x+y
arr=(np.fromfunction(fun,(4,4)))

In [20]:
arr[2][3]

5.0

In [21]:
arr[2,3]

5.0

In [23]:
countries=np.array(['India','USA','Australia','Greece','Bhutan'])
data=np.array([[1,2,3],[2,3,40],[23,43,21],[0,5,0],[5,5,5]])

In [24]:
countries=='India'

array([ True, False, False, False, False])

In [27]:
data[[ True, False, False, False, False]]

array([[1, 2, 3]])

In [29]:
data[countries=='USA']

array([[ 2,  3, 40]])

In [30]:
np.linspace(20,30)

array([20.        , 20.20408163, 20.40816327, 20.6122449 , 20.81632653,
       21.02040816, 21.2244898 , 21.42857143, 21.63265306, 21.83673469,
       22.04081633, 22.24489796, 22.44897959, 22.65306122, 22.85714286,
       23.06122449, 23.26530612, 23.46938776, 23.67346939, 23.87755102,
       24.08163265, 24.28571429, 24.48979592, 24.69387755, 24.89795918,
       25.10204082, 25.30612245, 25.51020408, 25.71428571, 25.91836735,
       26.12244898, 26.32653061, 26.53061224, 26.73469388, 26.93877551,
       27.14285714, 27.34693878, 27.55102041, 27.75510204, 27.95918367,
       28.16326531, 28.36734694, 28.57142857, 28.7755102 , 28.97959184,
       29.18367347, 29.3877551 , 29.59183673, 29.79591837, 30.        ])

In [31]:
np.linspace(20,30,10)

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [33]:
arr1=np.array([[1,2,3],[10,20,30]])
arr2=np.array([[5,5,5],[10,10,10]])
np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 5,  5,  5],
       [10, 10, 10]])

In [34]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  5,  5,  5],
       [10, 20, 30, 10, 10, 10]])

In [37]:
np.intersect1d(arr1,arr2)

array([10])

In [38]:
np.stack((arr1,arr2))

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 5,  5,  5],
        [10, 10, 10]]])

In [40]:
np.stack((arr1,arr2),axis=1)

array([[[ 1,  2,  3],
        [ 5,  5,  5]],

       [[10, 20, 30],
        [10, 10, 10]]])

In [41]:
np.ndim(np.stack((arr1,arr2)))

3

In [44]:
np.shape(np.stack((arr1,arr2)))

(2, 2, 3)